import os
import random
import datetime

# --- CONFIGURATION ---
OUTPUT_DIR = "src/content/projects"  # Where your theme expects projects
COUNT = 50                           # How many files to generate
TAG_LIST = ["Mechanical", "Thermal", "Software", "CFD", "Design", "Robotics", "Proto"]
IMAGE_PLACEHOLDERS = [
    "https://placehold.co/600x400/1a1a1a/ffffff?text=Project+Alpha",
    "https://placehold.co/600x400/2b2b2b/ffffff?text=Thermal+Sim",
    "https://placehold.co/600x400/3c3c3c/ffffff?text=Cad+Model",
    "https://placehold.co/600x400/4d4d4d/ffffff?text=Prototype",
]

def generate_frontmatter(index):
    # 1. Randomize Data
    title = f"Test Project {index:03d}"
    slug = f"test-project-{index:03d}"
    
    # Random date within last 2 years
    start_date = datetime.date(2023, 1, 1)
    end_date = datetime.date(2025, 12, 31)
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)
    
    # Pick 2-3 random tags
    project_tags = random.sample(TAG_LIST, k=random.randint(2, 3))
    tags_formatted = str(project_tags).replace("'", '"') # JSON style double quotes
    
    hero_image = random.choice(IMAGE_PLACEHOLDERS)

    # 2. Build Content
    content = f"""---
title: "{title}"
slug: "{slug}"
date: {random_date}
heroImage: "{hero_image}"
tags: {tags_formatted}
description: "Autogenerated dummy project to test layout and pagination limits."
---

## Overview

This is **dummy content** for {title}. 

It is designed to test:
1. **Pagination**: Does the grid break at 12 items?
2. **Tags**: Click on **{project_tags[0]}** to see if the filter works.
3. **Build Speed**: How fast does Astro process {COUNT} MDX files?

### Simulation Data

| Metric | Value |
| :--- | :--- |
| Load | {random.randint(10, 500)} Watts |
| Temp | {random.randint(20, 95)} °C |
| Status | {'PASS' if random.random() > 0.1 else 'FAIL'} |

> "This is a blockquote to check typography styles."

"""
    return slug, content

def main():
    # Ensure directory exists
    if not os.path.exists(OUTPUT_DIR):
        print(f"❌ Error: Could not find {OUTPUT_DIR}. Are you in the project root?")
        return

    print(f"🚀 Generating {COUNT} dummy projects...")
    
    for i in range(1, COUNT + 1):
        slug, content = generate_frontmatter(i)
        filename = f"{OUTPUT_DIR}/{slug}.mdx"
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
            
    print(f"✅ Done! Created {COUNT} files in {OUTPUT_DIR}")
    print("👉 Run 'npm run dev' to see them.")

if __name__ == "__main__":
    main()