name = "eriknorris"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Bind the R2 Bucket
[[r2_buckets]]
binding = "PROJECTS"
bucket_name = "projects"

# Bind the Session KV for Astro Server Mode
[[kv_namespaces]]
binding = "SESSION"
id = "SESSION_KV_ID"
preview_id = "SESSION_KV_PREVIEW_ID"
