import os
import sys
import datetime
import extract_msg
import re
# from markitdown import MarkItDown # (Optional: for future multimodal expansion)

def get_tags(subject, body_snippet):
    """
    Scans subject and partial body for high-value keywords and returns hashtags.
    """
    tags = set()
    subject_lower = subject.lower() if subject else ""
    
    # Keyword Map
    keywords = {
        '#type:status-report': ['status', 'weekly report', 'weekly update'],
        '#type:governance-mrb': ['mrb', 'ccb', 'change request', 'deviation', 'eco ', 'eco#', 'dcd'],
        '#type:meeting-notes': ['meeting', 'minutes', 'agenda', 'sync'],
        '#type:commercial-quote': ['quote', 'quotation', 'po#', 'purchase order', 'invoice', 'estimate'],
        '#type:product-requirements': ['prd', 'requirements', 'spec ', 'specification']
    }

    for tag, triggers in keywords.items():
        for trigger in triggers:
            if trigger in subject_lower:
                tags.add(tag)
                break
    
    # Date extraction (Simple month/year clustering if possible, but basic tags first)
    return list(tags)

def format_body_as_quote(text):
    """
    Wraps text in blockquotes to prevent LLM hallucination of context.
    """
    if not text: 
        return ""
    lines = text.split('\n')
    quoted_lines = [f"> {line}" for line in lines]
    return '\n'.join(quoted_lines)

def stitch_folder(folder_path):
    if not os.path.isdir(folder_path):
        print(f"Error: {folder_path} is not a directory.")
        return

    folder_name = os.path.basename(folder_path)
    output_file = os.path.join(folder_path, f"_INTELLIGENCE_{folder_name}.md")
    
    timestamp = datetime.datetime.now().isoformat()
    report_content = [
        f"# Intelligence Report: {folder_name}",
        f"> Generated by The Stitcher v2 (Refinery Edition) on {timestamp}",
        "\n## Manifest"
    ]

    files = sorted(os.listdir(folder_path))
    content_buffer = []

    print(f"Stitching {len(files)} files from {folder_name}...")

    for file in files:
        if file.startswith("_INTELLIGENCE"): continue
        
        file_path = os.path.join(folder_path, file)
        ext = os.path.splitext(file)[1].lower()
        
        # Header
        content_buffer.append(f"\n---\n### FILE: {file}")

        try:
            # TEXT / MARKDOWN / CODE
            if ext in ['.txt', '.md', '.csv', '.json', '.xml', '.py', '.js', '.ts', '.log']:
                with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
                    text = f.read()
                    content_buffer.append(f"---\n{text}")
                    report_content.append(f"- [ ] `{file}`")
            
            # OUTLOOK MSG
            elif ext == '.msg':
                try:
                    msg = extract_msg.Message(file_path)
                    msg_body = msg.body
                    msg_subject = msg.subject
                    msg_date = msg.date
                    msg_sender = msg.sender
                    
                    # 1. Auto-Tagging
                    tags = get_tags(msg_subject, msg_body[:200])
                    tag_line = f"**Tags:** {' '.join(tags)}\n" if tags else ""

                    # 2. Ghost Manifest (Attachments)
                    attachments = []
                    try:
                        for attachment in msg.attachments:
                            if hasattr(attachment, 'longFilename'):
                                attachments.append(attachment.longFilename)
                            elif hasattr(attachment, 'shortFilename'):
                                attachments.append(attachment.shortFilename)
                    except Exception:
                        pass # Squelch attachment errors
                    
                    attachment_line = f"**Ghost Attachments:** `{'`, `'.join(attachments)}`\n" if attachments else ""

                    # 3. Quoting Protocol
                    quoted_body = format_body_as_quote(msg_body)
                    
                    parsed_text = f"{tag_line}"
                    parsed_text += f"**Subject:** {msg_subject}\n"
                    parsed_text += f"**From:** {msg_sender}\n"
                    parsed_text += f"**Date:** {msg_date}\n\n"
                    parsed_text += f"{attachment_line}"
                    parsed_text += "---\n"
                    parsed_text += quoted_body
                    
                    content_buffer.append(parsed_text)
                    report_content.append(f"- [ ] `{file}` {tag_line}")
                    msg.close()
                except Exception as e:
                    content_buffer.append(f"---\n[Error parsing MSG file: {e}]")
                    report_content.append(f"- [x] `{file}` (Error)")
            
            # WORD DOCX
            elif ext == '.docx':
                try:
                    import docx
                    doc = docx.Document(file_path)
                    full_text = []
                    for para in doc.paragraphs:
                        full_text.append(para.text)
                    content_buffer.append('---\n' + '\n'.join(full_text))
                    report_content.append(f"- [ ] `{file}`")
                except Exception as e:
                     content_buffer.append(f"---\n[Error parsing DOCX: {e}]")

            # PDF (pypdf)
            elif ext == '.pdf':
                try:
                    import pypdf
                    reader = pypdf.PdfReader(file_path)
                    content_buffer.append(f"---\n[Metadata] Pages: {len(reader.pages)}\n")
                    
                    for i, page in enumerate(reader.pages):
                        text = page.extract_text()
                        if text:
                            content_buffer.append(f"\n--- Page {i+1} ---\n{text}")
                    report_content.append(f"- [ ] `{file}`")
                except Exception as e:
                    content_buffer.append(f"---\n[Error parsing PDF: {e}]")

            # PPTX (python-pptx)
            elif ext == '.pptx':
                try:
                    from pptx import Presentation
                    prs = Presentation(file_path)
                    content_buffer.append(f"---\n[Metadata] Slides: {len(prs.slides)}\n")
                    
                    for i, slide in enumerate(prs.slides):
                        slide_text = []
                        for shape in slide.shapes:
                            if hasattr(shape, "text"):
                                slide_text.append(shape.text)
                        
                        if slide_text:
                            content_buffer.append(f"\n--- Slide {i+1} ---\n" + "\n".join(slide_text))
                    report_content.append(f"- [ ] `{file}`")
                except Exception as e:
                    content_buffer.append(f"---\n[Error parsing PPTX: {e}]")

            # BINARY / LEGACY
            else:
                 content_buffer.append(f"---\n[Binary/Legacy File: {ext} - Content Not Extracted]")
                 report_content.append(f"- [ ] `{file}` (Binary)")
        
        except Exception as e:
            content_buffer.append(f"[Error reading file: {e}]")

    # Combine
    final_output = "\n".join(report_content) + "\n\n## CONTENT STREAM\n\n" + "\n".join(content_buffer)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(final_output)
    
    print(f"✅ Stitched into: {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python stitcher.py <absolute_folder_path>")
    else:
        stitch_folder(sys.argv[1])
