
import os
import sys
import datetime
import extract_msg
# from markitdown import MarkItDown # (Optional: for future multimodal expansion)

def stitch_folder(folder_path):
    if not os.path.isdir(folder_path):
        print(f"Error: {folder_path} is not a directory.")
        return

    folder_name = os.path.basename(folder_path)
    output_file = os.path.join(folder_path, f"_INTELLIGENCE_{folder_name}.md")
    
    timestamp = datetime.datetime.now().isoformat()
    report_content = [
        f"# Intelligence Report: {folder_name}",
        f"> Generated by The Stitcher (Python/Msg-Aware) on {timestamp}",
        "\n## Manifest"
    ]

    files = sorted(os.listdir(folder_path))
    content_buffer = []

    print(f"Stitching {len(files)} files from {folder_name}...")

    for file in files:
        if file.startswith("_INTELLIGENCE"): continue
        
        file_path = os.path.join(folder_path, file)
        ext = os.path.splitext(file)[1].lower()
        
        # Manifest Entry
        report_content.append(f"- [ ] `{file}`")

        # Header
        content_buffer.append(f"\n---\n### FILE: {file}\n---")

        try:
            # TEXT / MARKDOWN / CODE
            if ext in ['.txt', '.md', '.csv', '.json', '.xml', '.py', '.js', '.ts']:
                with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
                    content_buffer.append(f.read())
            
            # OUTLOOK MSG
            elif ext == '.msg':
                try:
                    msg = extract_msg.Message(file_path)
                    msg_body = msg.body
                    msg_subject = msg.subject
                    msg_date = msg.date
                    msg_sender = msg.sender
                    
                    parsed_text = f"**Subject:** {msg_subject}\n"
                    parsed_text += f"**From:** {msg_sender}\n"
                    parsed_text += f"**Date:** {msg_date}\n\n"
                    parsed_text += "**Body:**\n"
                    parsed_text += msg_body
                    
                    content_buffer.append(parsed_text)
                    msg.close()
                except Exception as e:
                    content_buffer.append(f"[Error parsing MSG file: {e}]")
            
            # WORD DOCX
            elif ext == '.docx':
                try:
                    import docx
                    doc = docx.Document(file_path)
                    full_text = []
                    for para in doc.paragraphs:
                        full_text.append(para.text)
                    content_buffer.append('\n'.join(full_text))
                except ImportError:
                     content_buffer.append("[Error: 'python-docx' library not found. Run: pip install python-docx]")
                except Exception as e:
                    content_buffer.append(f"[Error parsing DOCX file: {e}]")

            # PDF (pypdf)
            elif ext == '.pdf':
                try:
                    import pypdf
                    reader = pypdf.PdfReader(file_path)
                    content_buffer.append(f"\n[Metadata] Pages: {len(reader.pages)}\n")
                    
                    for i, page in enumerate(reader.pages):
                        text = page.extract_text()
                        if text:
                            content_buffer.append(f"\n--- Page {i+1} ---\n{text}")
                except ImportError:
                    content_buffer.append("[Error: 'pypdf' library not found.]")
                except Exception as e:
                    content_buffer.append(f"[Error parsing PDF: {e}]")

            # PPTX (python-pptx)
            elif ext == '.pptx':
                try:
                    from pptx import Presentation
                    prs = Presentation(file_path)
                    content_buffer.append(f"\n[Metadata] Slides: {len(prs.slides)}\n")
                    
                    for i, slide in enumerate(prs.slides):
                        slide_text = []
                        for shape in slide.shapes:
                            if hasattr(shape, "text"):
                                slide_text.append(shape.text)
                        
                        if slide_text:
                            content_buffer.append(f"\n--- Slide {i+1} ---\n" + "\n".join(slide_text))
                except ImportError:
                    content_buffer.append("[Error: 'python-pptx' library not found.]")
                except Exception as e:
                    content_buffer.append(f"[Error parsing PPTX: {e}]")

            # BINARY / LEGACY
            else:
                 content_buffer.append(f"[Binary/Legacy File: {ext} - Content Not Extracted]")
        
        except Exception as e:
            content_buffer.append(f"[Error reading file: {e}]")

    # Combine
    final_output = "\n".join(report_content) + "\n\n## CONTENT STREAM\n\n" + "\n".join(content_buffer)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(final_output)
    
    print(f"✅ Stitched into: {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python stitcher.py <absolute_folder_path>")
    else:
        stitch_folder(sys.argv[1])
