
import fs from 'fs/promises';
import path from 'path';

/**
 * THE STITCHER
 * Unifies fragmented documentation into a single "Intelligence Stream" for NotebookLM.
 * 
 * Usage: node stitcher.js <folder_path>
 */

const VALID_EXTENSIONS = ['.txt', '.md', '.json', '.xml', '.csv', '.rtf', '.doc', '.docx', '.msg'];
// Note: .doc/.docx/.msg parsing requires external libs not present, 
// so we will just log their existence for now, or read them if they are plain text.
// For V1, we focus on reading text-readable files.

async function stitchFolder(folderPath) {
    try {
        const stats = await fs.stat(folderPath);
        if (!stats.isDirectory()) {
            console.error(`Error: ${folderPath} is not a directory.`);
            return;
        }

        const files = await fs.readdir(folderPath);
        const folderName = path.basename(folderPath);
        const outputFile = path.join(folderPath, `_INTELLIGENCE_${folderName}.md`);

        let reportContent = `# Intelligence Report: ${folderName}\n\n`;
        reportContent += `> Generated by The Stitcher on ${new Date().toISOString()}\n\n`;
        reportContent += `## Manifest\n`;

        const contentBuffer = [];

        for (const file of files) {
            if (file.startsWith('_INTELLIGENCE')) continue; // Don't eat yourself

            const ext = path.extname(file).toLowerCase();
            const filePath = path.join(folderPath, file);

            // manifest entry
            reportContent += `- [ ] \`${file}\`\n`;

            if (['.txt', '.md', '.csv', '.json'].includes(ext)) {
                try {
                    const content = await fs.readFile(filePath, 'utf-8');
                    contentBuffer.push(`\n---\n### FILE: ${file}\n---\n${content}\n`);
                } catch (err) {
                    contentBuffer.push(`\n---\n### FILE: ${file} (READ ERROR)\n---\nError reading file: ${err.message}\n`);
                }
            } else {
                // For binaries or unparsed formats, just separate them
                contentBuffer.push(`\n---\n### FILE: ${file} (BINARY/UNPROCESSED)\n---\n[File verification only. Refer to original asset.]\n`);
            }
        }

        reportContent += `\n---\n## CONTENT STREAM\n\n`;
        reportContent += contentBuffer.join('\n');

        await fs.writeFile(outputFile, reportContent);
        console.log(`✅ Stitched ${files.length} files into: ${outputFile}`);

    } catch (err) {
        console.error("Stitcher Failed:", err);
    }
}

const targetArgs = process.argv.slice(2);
if (targetArgs.length === 0) {
    console.log("Usage: node stitcher.js <absolute_folder_path>");
} else {
    stitchFolder(targetArgs[0]);
}
